---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jbarous-token
spec:
  encryptedData:
    token: AgCJgAA1ISnOoxiPDkzq45JblN3OtSU5Z2pBfw0jT58+XOmyHlyO1nS2Zf/xqTWiZ14TDzKci1wULqjEbrWhUleDEANw0DM6d836mja1x0yJIANR9YwHlYcO5HM4u8vdyt/CF7h9NtNJ350YUZr9s7LdsCXBtkDw6MY5DBbq6MQlQs39plcmWqdsK3OZuBJP4bSzdNppE1oxDDh0Mwl3wH8LP/x1vF2wlIOnWwwnH/5Db7+P7QmSw9eAT0ztqWsPzNMd3qdz6SMRV8RTG85RbHCjabyDa6ERmGoZurKL+wvvfWmhSrSCEIoPMkkD5u074RRFpEBE2rUXFZoyTe5gwe30mGRuIFogxjmPUhxj59TPr8JqNW6qAjUvMo7srXyebrBlOD2db00Mhjd7WTvWU1zcAPX0/Vo1rfTmLhhYrJVkMUJD2BXFS63nNUQp4XhT8cCY6fiyWMLmHmoeYATgB6EU7t4JVaeQDPAvcyk4HuqLpwPFW3mpGXQYqYL/LAw0mYdVMvLdJ5O/e80k+hKkIA3TXMa3yCXzL6rOsOOn1+JpZlIHflMbV2pUyARKvSCGtN7gI3tIGFXKwt4dwO+EEjX+cFdthtgfAN5+tLY4FOaH3ewNNu3N5kjp2NhY3xaFHOcoWSWuCv+63YjmGV64obz1U4r2y3zBCOUtBh85CoyE1wGpLIqY2P52s/OZBIXvlJ8VCSLed+jy1hDUEXarmoSGhGbY+I/z3i2pIapPVz41ttgrRJGpD2FS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: jbarous-token
